export enum DocumentsType {
  PASSPORT = 'PASSPORT',
  ID_CARD = 'ID_CARD',
  DRIVER_LICENSE = 'DRIVER_LICENSE',
  TAX_FORM = 'TAX_FORM',
  AGREEMENT = 'AGREEMENT',
  PROOF_OF_ADDRESS = 'PROOF_OF_ADDRESS',
  ID_DOCUMENT = 'ID_DOCUMENT',
  STATEMENT = 'STATEMENT',
  OTHER = 'OTHER',
}
