export enum OtpPurpose {
  SIGNUP = 'SIGNUP',
  SIGNIN = 'SIGNIN',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  AUTH_EXISTING_CUSTOMER = 'AUTH_EXISTING_CUSTOMER',
  RESEND_EMAIL_VERIFICATION = 'RESEND_EMAIL_VERIFICATION',
}
